package io.lindhagen.aoc.aoc2025.day7

import io.lindhagen.aoc.aoc2025.BaseTest
import io.lindhagen.aoc.aoc2025.Task


internal class Day7Test : BaseTest<Long> {
    override val tester = Day7

    override val sample = Task(
      input = """
      .......S.......
      ...............
      .......^.......
      ...............
      ......^.^......
      ...............
      .....^.^.^.....
      ...............
      ....^.^...^....
      ...............
      ...^.^...^.^...
      ...............
      ..^...^.....^..
      ...............
      .^.^.^.^.^...^.
      ...............
      """.trimIndent().trimMargin(),
      task1 = 4277556L,
      task2 = 14L,
    )
    override val actual = Task(
      input = "day7",
      task1 = 5782351442566L,
      task2 = 8948L,
    )
}
